site_name: My Docs
theme:
  name: material
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.sections
  icon:
    admonition:
      info: material/sim-alert


  palette: 
     # Palette toggle for light mode
    - scheme: default
      primary: teal
      accent: orange
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      primary: teal
      accent: orange
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

markdown_extensions:
- pymdownx.highlight:
    anchor_linenums: true
    line_spans: __span
    pygments_lang_class: true
- pymdownx.inlinehilite
- pymdownx.snippets
- pymdownx.superfences
- pymdownx.tabbed:
      alternate_style: true
- admonition

plugins:
  - search
  - awesome-pages