site_name: pyscript.recipes
site_url: https://pyscript.recipes/
theme:
  name: material
  logo: assets/book-solid.svg
  favicon: assets/pylogo.svg
  custom_dir: overrides
  features:
    - navigation.tracking
    - navigation.indexes
  icon:
    admonition:
      info: material/sim-alert

  palette: 
     # Palette toggle for light mode
    - scheme: default
      primary: teal
      accent: orange
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      primary: teal
      accent: orange
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

markdown_extensions:
- pymdownx.highlight:
    anchor_linenums: true
    line_spans: __span
    pygments_lang_class: true
- pymdownx.inlinehilite
- pymdownx.snippets
- pymdownx.superfences
- pymdownx.tabbed:
      alternate_style: true
- admonition
- attr_list
- pymdownx.emoji:
    emoji_index: !!python/name:material.extensions.emoji.twemoji
    emoji_generator: !!python/name:material.extensions.emoji.to_svg

plugins:
  - search
  - awesome-pages
  - mike:
      canonical_version: "latest"
  - social

extra:
  social:
    - icon: fontawesome/brands/github 
      link: https://github.org/jeffersglass
  version:
    provider: mike
  analytics:
    provider: google
    property: G-Y28QP0NFSN

copyright: Copyright &copy; 2024 Jeff Glass - <a href="/about#license">License Details</a>
